### ISSUE TITLE
Add User dialog creates invalid users that won't actually work to auth with MongoDB

### ISSUE THREAD

**Issue by juliashibalko** [paralect/robomongo#1041]
Robomongo versions checked: 0.8.5 at first, then latest 0.9.0-RC4

https://twitter.com/Adam_Falafel/status/702258107326533633

**Comment by AdamAndersonFalafelSoftware** [comment]
Steps:(Windows version)

* MongoDB version 2.6.11
* Connect to a DB
* Expand to the Users folder
* Right-click and choose Add User
* Enter Username and Password; select a few roles
* Click OK
* Note that the User document appears as a child under the Users folder in the left pane
* Right-clicking on the Users folder and choosing View Users will display the created User. Note that the command executed is db.system.users.find()
* Test auth by entering `db.auth('<username>', '<password>')` into the console
* Observe that the response is `Error: auth failed 0`

You can create a user that *does* work with db.auth() by using db.createUser(). You can list these users with db.getUsers().

**Comment by juliashibalko** [comment]
@AdamAndersonFalafelSoftware  Thanks Adam for adding details! We'll address that in the upcoming releases.

**Comment by juliashibalko** [comment]
https://github.com/paralect/robomongo/issues/638

**Comment by christangga** [comment]
is this solved in the new release?

**Comment by simsekgokhan** [comment]
Hi @christangga , unfortunately not, the current heavy weight work is delivering critical features like Replcia Sets and Export/Import asap. User management is planned to after those. 
Please see here: https://github.com/paralect/robomongo#whats-planned-for-the-next-releases

**Comment by Aninstance** [comment]
This issue still persists, Robomongo 1.0.0, MongoDB 2.6.12.

**Comment by alandroid** [comment]
Issue persists with Robo 3T 1.1.1 and MongoDB 3.4.6 ('db version' from mongod -v)

Was not able to use Robo 3T GUI to create users via 'Add User' menu,
had to use db.CreateUser() and then manual craft the document/bson.

**Comment by Kroderia** [comment]
Same issue as @alandroid with Robo 3T 1.1.1 (Windows 10) and Mongodb 3.2.13

**Comment by dickreuter** [comment]
Still not solved

**Comment by hiasel** [comment]
Unfortunately the issue is still not solved.
Robo3T: Version 1.1.1 for Mac
Mongo: 3.4.10

As @alandroid pointed out, a current workaround is to create users inside the command-window of Robot3T. Adding a user called "myuser" to the db "mydb" looks like this:
```
use mydb
db.createUser( { user: "myuser",
                 pwd: "mypw",
                 roles: [ { role: "readWrite", db: "mydb" }] },
               { w: "majority" , wtimeout: 5000 } 
              )
```

See: https://docs.mongodb.com/manual/reference/method/db.createUser/

**Comment by Trapholov** [comment]
Still not solved

**Comment by dejayc** [comment]
If this joke of a feature is still not implemented two years later, maybe the developers should just remove the "Add User" option from the menu?

**Comment by nanomo** [comment]
Still not solved, lost big time with this bug, please add at least a modal warning with a message!

**Comment by vetinary** [comment]
OH! MY! GOD! It took me half a day to find this topic and find out, that problem was not in my software, but in Robo 3T app. 🤦‍♂️

**Comment by Tarpsvo** [comment]
Well, I joined the lost two hours past midnight club here. This should be high priority.

**Comment by NobleKayHara** [comment]
Really though??? Why is it even there in the first place. Goodness

**Comment by dejayc** [comment]
It's there to confuse new users for years on end.

**Comment by ardennext99** [comment]
Still present in my configuration:

Robo 3T 1.2.1 + MongoDB 2.7.0

If I create an user in Robo 3T by "Add user" function, I cannot find it by "db.getUsers()" command line.
If I create an user by  command line, when i refresh the Robo 3T users compaer "mongodb wrong type for field (_id) string = 7"

When we can hope a fix?
Robo 3T should be the "Sql Server Management Studio" for MongoDB, but with this bug.....

**Comment by gp2015** [comment]
Also having this issue. When I create a user from the shell, no problem, but using the GUI the user created is not able to authenticate.

**Comment by alandroid** [comment]
Still not solved. This software is outdated.

**Comment by gp2015** [comment]
Since this issue looks kind of abandoned, are there any open source / free alternatives that aren't Studio 3t?

**Comment by macxu** [comment]
still not solved.... I spent more than an hour on it and it turned out to be a known issue on the software...

**Comment by PathToLife** [comment]
Wasted 2 hours of my time. Rip. Is this fixed in the overpriced Studio3T?

**Comment by PathToLife** [comment]
Hey fix found
Use:
https://github.com/nosqlclient/nosqlclient

**Comment by simsekgokhan** [comment]
Hi All, we are very sorry for the long delay. 
We have some fixes and new features related to user management. Currently, the limitation is Robo supports fixed usersource for user creation. Please try our beta:

Robo 3T 1.3 Beta
https://github.com/Studio3T/robomongo/releases/tag/v1.3.0-beta

**Comment by september28** [comment]
Hi Guys, I have suffered this same issue. Is there a way I can remove the erroneous user that Robo3T has created? I don't seem to have permissions to delete the user now, and I am left with a "System" folder in the (relevant) database containing a "system.users" collection, and a "Users" folder under the database with my erroneous user. If I try to right click the user and click "Drop User" I get the message "Failed to drop user 'username-here'. Error: Not authorized to remove from database-name.system.users".
in the CLI:
use database-name
db.getUsers
produces an empty array so mongodb itself can't seem to delete it...

Any help appreciated.

**Comment by brucecollins** [comment]
I'd say this is a bit of an issue as I spent an entire day troubleshooting this capability.  Is there any chance robo3T UI can disable the function to avoid sending others on a wild goose chase?  Lastly, if robo3t is not a viable Ui - which one should I install and use?  Thanks!

**Comment by simsekgokhan** [comment]
Hi @september28 , @brucecollins . Very sorry to hear that you wasted your time. 
To fix (or disable that functionality) can you tell us how to reproduce your problems? 
- Steps to reproduce
- Robo 3T version
- MongoDB version and db details (Atlas, local, single, replica set etc..)
- OS version (Win 7, Ubuntu 18.04 etc..)

Please also note that we have some users related fixes on Robo 3T 1.3 https://blog.robomongo.org/robo-3t-1-3/#c1

I just created a user on my local server. Connection works, I can drop the user and can see the created user: 

```
> use admin
switched to db admin
>
> db.getUsers()
 [
      ...
      {
               "_id" : "admin.bb",
               "userId" : UUID("9c98b305-94a3-4c94-b1a1-3e04d21f8e59"),
               "user" : "bb",
               "db" : "admin",
               "roles" : [
                       {
                               "role" : "readWriteAnyDatabase",
                               "db" : "admin"
                       }
               ],
               "mechanisms" : [
                       "SCRAM-SHA-1",
                       "SCRAM-SHA-256"
               ]
       }
]
```
