### ISSUE TITLE
Query failure if password contains apostrophe: "Connection error. Uninitialized mongo scope"

### ISSUE THREAD

**Issue by vincebowdren** [paralect/robomongo#1300]
If a user's password includes the single-quote (apostrophe) character ' , then it is possible for RoboMongo to connect as this user, but when you try to execute a query in a tab it fails with the following feedback dialog:

    ---------------------------
    Error
    ---------------------------
    Failed to execute script.

    Error:
    Connection error. Uninitialized mongo scope.
    ---------------------------
    OK   
    ---------------------------

The window also shows "Script executed successfully, but there are no results to show."

Steps to reproduce:

1. In the mongo shell, create a user with a suitable role and a password which includes an apostrophe (see attached screenshot 101)
2. In the mongo shell, verify the account can be used to authenticate and to execute a query OK (screenshot 102)
3. In RoboMongo, configure a connection which authenticates with this user account; the Test button confirms that it can connect OK (screenshot 103)
4. In RoboMongo, open this connection; it connects OK, and can show collections OK (screenshot 104)
5. In RoboMongo, View Documents on one of the listed collections
_Expected result: the find() query returns the documents in the collections_
**Actual result:   the find() query fails with the error as described above (screenshot 105)**

Note: this problem does _not_ occur if the password has no apostrophe; I have tested with a wide variety of other punctuation characters, but only the apostrophe seems to cause RoboMongo's connection to fail.

Environment:

- server: MongoDB 3.0.12
- app: RoboMongo 1.0-RC1 on Windows 10 64-bit
- authentication method: SCRAM-SHA1..

**Comment by simsekgokhan** [comment]
Hi @vincebowdren , thanks for reporting the problem.
Can you double check the screenshots? Were they supposed to be links?

**Comment by vincebowdren** [comment]
Sorry, forgot to attach them :(-
Fixed now :)-

**Comment by simsekgokhan** [comment]
Hi @vincebowdren , I have reproduced the problem. We will investigate.
Can you let us know if you are able to do your work if you do not use apostrophe in password for now?

**Comment by vincebowdren** [comment]
Oh yes, I've changed the account password to something without any apostrophes, and we're happily getting on with things. Thanks for asking!

**Comment by Lucas63** [comment]
This error still present. My username, my password doesnt have any special characters.

**Comment by RashmiJha1986** [comment]
Do we have any updates on this issue? My password doesn't have an apostrophe but I am still getting the error mentioned above.

**Comment by Immortalt** [comment]
This error still present.

**Comment by deepsnow** [comment]
Still seeing this in Robo 3t 1.2.1.

**Comment by devgig** [comment]
Seeing this issue in Robo 3t 1.3

**Comment by ssonnad** [comment]
i had some backslash in the password, removing which it started working.

**Comment by lucasrcosta** [comment]
Still seeing this issue in Robo 3t 1.3.1

**Comment by DeepakDonde** [comment]
Got the same issue with Robo 3T 1.3....it was working few days ago.
Only getting it for remote db...works fine on localhost.

**Comment by dmitry-kostin** [comment]
wtf this issue 3 years old and nobody cares about it
